Repository fga-eps-mds/2020.2-Hortum, pull requests merged in 2021-03, with the labels that each got.

#54 #41 incrementação do documento de visao
  docs/Documento_de_visao.md
Labels: Sprint 3, documentation

#56 #44 Adição de tópicos sobre banco de dados
  docs/Documento_de_arquitetura.md
  docs/img/diagrama_banco_de_dados.png
Labels: Sprint 3, documentation

#55 #43 Canvas do Produto
  docs/Canvas.md
  docs/img/Canvas.png
  mkdocs.yml
Labels: Sprint 3, documentation

#53 #42 Implementação docker backend
  Dockerfile
  README.md
  docker-compose.yml
  mkdocs.yml
  src/hortum/settings.py
  startup.sh
Labels: Sprint 3, development

#57 #31 Politica de Contribuicao
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/Politica_de_Contribuicao.md
  mkdocs.yml
Labels: Sprint 3, documentation

#71 #59 Adição da sprint retrospective e sprint review 3
  docs/img/burndown_3.png
  docs/img/conhecimentos_3.png
  docs/img/retrospective_3.png
  docs/img/velocity_3.png
  docs/sprints/sprint_3/Review_sprint_3.md
  mkdocs.yml
Labels: SM, Sprint 4, documentation

#72 #60 Adição do planning da sprint 4
  docs/sprints/sprint_4/Planning_sprint_4.md
  mkdocs.yml
Labels: SM, Sprint 4, documentation

#73 #65 - Adição do diagrama de casos de uso
  docs/Documento_de_arquitetura.md
  docs/img/diagrama_casos_de_uso.png
Labels: Sprint 4, documentation

#75 #67 Melhorando documentação do banco de dados
  docs/Documento_de_arquitetura.md
  docs/img/diagrama_entidade_relacionamentos.png
Labels: Sprint 4, documentation

#76 #45 Adicionado protótipo de alta fidelidade
  docs/Prototipo.md
  docs/img/Alta_fidelidade.png
Labels: Sprint 4, documentation

#74 #58 Criando models do banco de dados e serializando
  requirements.txt
  src/hortum/announcement/__init__.py
  src/hortum/announcement/admin.py
  src/hortum/announcement/apps.py
  src/hortum/announcement/migrations/0001_initial.py
  src/hortum/announcement/migrations/0002_auto_20210308_2222.py
  src/hortum/announcement/migrations/__init__.py
  src/hortum/announcement/models.py
  src/hortum/announcement/serializer.py
  src/hortum/announcement/tests.py
  src/hortum/announcement/views.py
  src/hortum/assets/apps.py
  src/hortum/assets/models.py
  src/hortum/customer/__init__.py
  src/hortum/customer/admin.py
  src/hortum/customer/apps.py
  src/hortum/customer/migrations/0001_initial.py
  src/hortum/customer/migrations/__init__.py
  src/hortum/customer/models.py
  src/hortum/customer/serializer.py
  src/hortum/customer/tests.py
  src/hortum/customer/views.py
  src/hortum/picture/__init__.py
  src/hortum/picture/admin.py
  src/hortum/picture/apps.py
  src/hortum/picture/migrations/0001_initial.py
  src/hortum/picture/migrations/__init__.py
  src/hortum/picture/models.py
  src/hortum/picture/serializer.py
  src/hortum/picture/tests.py
  src/hortum/picture/views.py
  src/hortum/productor/__init__.py
  src/hortum/productor/admin.py
  src/hortum/productor/apps.py
  src/hortum/productor/migrations/0001_initial.py
  src/hortum/productor/migrations/0002_auto_20210308_2157.py
  src/hortum/productor/migrations/0003_auto_20210308_2315.py
  src/hortum/productor/migrations/__init__.py
  src/hortum/productor/models.py
  src/hortum/productor/serializer.py
  src/hortum/productor/tests.py
  src/hortum/productor/views.py
  src/hortum/settings.py
  src/hortum/users/__init__.py
  src/hortum/users/admin.py
  src/hortum/users/apps.py
  src/hortum/users/migrations/__init__.py
  src/hortum/users/models.py
  src/hortum/users/tests.py
  src/hortum/users/views.py
Labels: Sprint 4, development

#77 #66 identidade visual do projeto
  README.md
  docs/Guia_de_estilo_e_identidade_visual.md
  docs/img/botoes.png
  docs/img/campo_anuncio.png
  docs/img/campo_formulario.png
  docs/img/cor_logo.png
  docs/img/cor_logo_secundaria.png
  docs/img/cor_rosa.png
  docs/img/leaves.png
  docs/img/lemons.png
  docs/img/logo.png
  docs/img/navbar.png
  mkdocs.yml
Labels: Sprint 4, documentation

#87 #84 Documentando o review e retrospective da sprint 4
  docs/img/burndown_4.png
  docs/img/retrospective_4.png
  docs/img/velocity_4.png
  docs/sprints/sprint_4/Review_sprint_4.md
  mkdocs.yml
Labels: SM, Sprint 5, documentation

#86 #82 Implementação do Abstract User
  src/hortum/announcement/migrations/0001_initial.py
  src/hortum/announcement/migrations/0002_auto_20210308_2222.py
  src/hortum/announcement/models.py
  src/hortum/announcement/serializer.py
  src/hortum/customer/migrations/0001_initial.py
  src/hortum/customer/models.py
  src/hortum/customer/serializer.py
  src/hortum/picture/migrations/0001_initial.py
  src/hortum/productor/apps.py
  src/hortum/productor/migrations/0001_initial.py
  src/hortum/productor/migrations/0002_auto_20210308_2157.py
  src/hortum/productor/migrations/0003_auto_20210308_2315.py
  src/hortum/productor/models.py
  src/hortum/productor/serializer.py
  src/hortum/settings.py
  src/hortum/users/admin.py
  src/hortum/users/migrations/0001_initial.py
  src/hortum/users/models.py
  src/hortum/users/serializer.py
Labels: Backend, Sprint 5, development

#88 #85 Documentação do planning da sprint 5
  docs/sprints/sprint_4/Review_sprint_4.md
  docs/sprints/sprint_5/Planning_sprint_5.md
  mkdocs.yml
Labels: SM, Sprint 5, documentation

#109 #79 Revisão de documentos da wiki
  .github/pull_request_template.md
  docs/Documento_de_arquitetura.md
  docs/Documento_de_visao.md
  docs/Documento_metodologia.md
  docs/sprints/sprint_4/Planning_sprint_4.md
Labels: Sprint 5, documentation

#108 #61 [US] - Backend do cadastro de usuário
  Dockerfile
  docker-compose.yml
  requirements.txt
  src/hortum/announcement/migrations/0001_initial.py
  src/hortum/customer/migrations/0001_initial.py
  src/hortum/customer/migrations/0002_customer_idprodfav.py
  src/hortum/customer/migrations/0003_customer_user.py
  src/hortum/customer/serializer.py
  src/hortum/customer/urls.py
  src/hortum/customer/views.py
  src/hortum/customer/viewsets.py
  src/hortum/picture/migrations/0001_initial.py
  src/hortum/productor/migrations/0001_initial.py
  src/hortum/productor/migrations/0002_productor_user.py
  src/hortum/productor/serializer.py
  src/hortum/productor/urls.py
  src/hortum/productor/views.py
  src/hortum/productor/viewsets.py
  src/hortum/settings.py
  src/hortum/urls.py
  src/hortum/users/migrations/0001_initial.py
  src/hortum/users/models.py
  src/hortum/users/serializer.py
  src/hortum/users/urls.py
  src/hortum/users/views.py
  src/hortum/users/viewsets.py
  src/scripts/clear_migrations.sh
  src/scripts/create_superuser.sh
  src/scripts/startup.sh
Labels: Backend, Sprint 4, development, user story

#110 #78 Melhoria dos README's
  README.md
  docs/img/logo.png
Labels: Sprint 5, documentation

#111 #80 Customização do mkdocs
  docs/fonts/Comfortaa-Regular.ttf
  docs/fonts/Roboto-Regular.ttf
  docs/index.md
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: Sprint 5, documentation

#120 #119 Documentação da review e retrospective da sprint 5
  docs/Product_Backlog.md
  docs/img/burndown_5.png
  docs/img/retrospective_5.png
  docs/img/velocity_5.png
  docs/sprints/sprint_5/Review_sprint_5.md
  mkdocs.yml
Labels: SM, Sprint 6, documentation

#121 #118 Documentação do planning da sprint 6
  docs/sprints/sprint_6/Planning_sprint_6.md
  mkdocs.yml
Labels: SM, Sprint 6, documentation

#112 #81 [US03] - Login de Conta
  src/hortum/announcement/migrations/0001_initial.py
  src/hortum/customer/migrations/0001_initial.py
  src/hortum/customer/migrations/0002_customer_idprodfav.py
  src/hortum/customer/migrations/0003_customer_user.py
  src/hortum/customer/serializer.py
  src/hortum/picture/migrations/0001_initial.py
  src/hortum/productor/migrations/0001_initial.py
  src/hortum/productor/migrations/0002_productor_user.py
  src/hortum/productor/serializer.py
  src/hortum/settings.py
  src/hortum/urls.py
  src/hortum/users/migrations/0001_initial.py
  src/hortum/users/models.py
  src/hortum/users/viewsets.py
Labels: Backend, Sprint 5, development

#123 #113 Conexão login registro
  src/hortum/announcement/migrations/0001_initial.py
  src/hortum/customer/migrations/0001_initial.py
  src/hortum/customer/migrations/0002_customer_idprodfav.py
  src/hortum/customer/migrations/0003_customer_user.py
  src/hortum/picture/migrations/0001_initial.py
  src/hortum/productor/migrations/0001_initial.py
  src/hortum/productor/migrations/0002_productor_user.py
  src/hortum/productor/serializer.py
  src/hortum/users/migrations/0001_initial.py
  src/hortum/users/models.py
  src/hortum/users/serializer.py
Labels: Sprint 6, enhancement

#124 #114 Retorno da rota de login
  src/hortum/urls.py
  src/hortum/users/serializer.py
  src/hortum/users/viewsets.py
Labels: Backend, Sprint 6, development, enhancement

#126 #116 Revisão do Documento de Arquitetura
  docs/Documento_de_arquitetura.md
  docs/img/diagrama_banco_de_dados.png
  docs/img/diagrama_casos_de_uso.png
  docs/img/diagrama_de_pacotes.png
  docs/img/diagrama_entidade_relacionamentos.png
  docs/img/visao_logica.png
Labels: Sprint 6, documentation

#122 #115 Substituindo imagens por frame do Figma
  docs/Prototipo.md
Labels: Sprint 6, documentation

#134 #132 Adição da review/retrospective da sprint 6
  docs/img/burndown_6.png
  docs/img/conhecimentos_5.png
  docs/img/retrospective_6.png
  docs/img/velocity_6.png
  docs/sprints/sprint_5/Review_sprint_5.md
  docs/sprints/sprint_6/Review_sprint_6.md
  mkdocs.yml
Labels: SM, Sprint 7, documentation

#135 #133 Adição do planning da sprint 7
  docs/sprints/sprint_7/Planning_sprint_7.md
  mkdocs.yml
Labels: SM, Sprint 7, documentation
