Repository fga-eps-mds/2020.2-Hortum, pull requests merged in 2021-04, with the labels that each got.

#137 #130 Refatorando as rotas de produtor, e cadastro de comprador.
  src/hortum/customer/urls.py
  src/hortum/productor/urls.py
  src/hortum/productor/viewsets.py
  src/hortum/users/urls.py
Labels: Backend, Sprint 7, development

#147 #139 Atualizando parcerias chaves e estrutura de custos
  docs/Canvas.md
  docs/img/Canvas.png
Labels: Sprint 8, documentation

#148 #146 Adição da review/retrospective da sprint 7
  docs/img/burndown_7.png
  docs/img/conhecimentos_7.png
  docs/img/retrospective_7.png
  docs/img/velocity_7.png
  docs/sprints/sprint_7/Review_sprint_7.md
  mkdocs.yml
Labels: SM, Sprint 8, documentation

#149 #145 Adição do planning da sprint 8
  docs/sprints/sprint_8/Planning_sprint_8.md
  mkdocs.yml
Labels: SM, Sprint 8, documentation

#150 #143 Adição do Hotfix template
  .github/ISSUE_TEMPLATE/hotfix_template.md
Labels: Sprint 8, documentation

#151 #96 [US09] - Excluir anúncio
  src/hortum/announcement/serializer.py
  src/hortum/announcement/tests.py
  src/hortum/announcement/urls.py
  src/hortum/announcement/viewsets.py
  src/hortum/customer/serializer.py
  src/hortum/productor/serializer.py
Labels: Backend, Sprint 8, development, user story

#152 #138 Melhorando Visão Lógica
  docs/Documento_de_arquitetura.md
Labels: documentation

#153 #94 [US08] - Editar anúncio
  src/hortum/announcement/serializer.py
  src/hortum/announcement/tests.py
  src/hortum/announcement/urls.py
  src/hortum/announcement/viewsets.py
Labels: Backend, Sprint 8, development, user story

#156 #144 estudo implementacao ci e cd
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  heroku.yml
  requirements.txt
  src/hortum/settings.py
  src/scripts/release.sh
Labels: DevOps, Sprint 8, development

#154 #142 Backend para o login automático
  src/hortum/urls.py
  src/hortum/users/serializer.py
  src/hortum/users/viewsets.py
Labels: Backend, Sprint 8, development

#155 #140 Testes unitários de issues passadas
  src/hortum/announcement/tests.py
  src/hortum/customer/tests.py
  src/hortum/productor/tests.py
  src/hortum/users/tests.py
Labels: Backend, Sprint 8

#167 #165 Documentação da review/retrospective da sprint 8
  docs/img/burndown_8.png
  docs/img/retrospective_8.png
  docs/img/riscos_8.png
  docs/img/velocity_8.png
  docs/sprints/sprint_8/Review_sprint_8.md
  mkdocs.yml
Labels: SM, Sprint 9, documentation

#169 #166 Adicionando documento sobre o planning
  docs/sprints/sprint_9/Planning_sprint_9.md
  mkdocs.yml
Labels: SM, Sprint 9, documentation

#168 #159 Realizando alteraçao no fluxograma visao logica
  docs/Documento_de_arquitetura.md
  docs/img/visao_logica.png
Labels: Sprint 9, documentation

#170 Feature/162 codequality ci cd
  .github/workflows/ci.yml
  src/hortum/announcement/admin.py
  src/hortum/announcement/models.py
  src/hortum/announcement/serializer.py
  src/hortum/announcement/tests.py
  src/hortum/announcement/urls.py
  src/hortum/announcement/viewsets.py
  src/hortum/customer/admin.py
  src/hortum/customer/models.py
  src/hortum/customer/urls.py
  src/hortum/customer/viewsets.py
  src/hortum/picture/admin.py
  src/hortum/picture/models.py
  src/hortum/picture/tests.py
  src/hortum/picture/views.py
  src/hortum/productor/admin.py
  src/hortum/productor/models.py
  src/hortum/productor/tests.py
  src/hortum/productor/urls.py
  src/hortum/productor/viewsets.py
  src/hortum/settings.py
  src/hortum/users/tests.py
  src/hortum/users/viewsets.py
Labels: DevOps, Sprint 9

#171 #158 Refatoração das viewsets
  src/hortum/announcement/serializer.py
  src/hortum/announcement/tests.py
  src/hortum/announcement/urls.py
  src/hortum/announcement/viewsets.py
  src/hortum/productor/tests.py
  src/hortum/productor/urls.py
  src/hortum/productor/viewsets.py
Labels: Backend, Sprint 9

#172 #97 [US11] - Procurar produto
  src/hortum/announcement/tests.py
  src/hortum/announcement/urls.py
  src/hortum/announcement/viewsets.py
Labels: Backend, Sprint 9, development, user story

#174 #164 Implemetação de testes que faltavam
  src/hortum/announcement/tests.py
  src/hortum/customer/tests.py
  src/hortum/productor/tests.py
  src/hortum/users/tests.py
  src/hortum/users/urls.py
  src/hortum/users/viewsets.py
Labels: Backend, Sprint 9, development

#173 #160 Melhoria Canvas
  docs/Canvas.md
  docs/img/Canvas.png
Labels: Sprint 9, documentation

#176 #162 Automatização deploy CD - coverage CI
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  README.md
  requirements.txt
Labels: DevOps, Sprint 9

#177 [HOTFIX] #162 colocando o Ci para rodar em push na main
  .github/workflows/ci.yml
Labels: Hotfix

#175 #96 [US10] - Pesquisar Produtor
  src/hortum/productor/serializer.py
  src/hortum/productor/tests.py
  src/hortum/productor/urls.py
  src/hortum/productor/viewsets.py
Labels: Backend, Sprint 9, development, user story

#179 #157 Linkar Backend com a homepage do Produtor
  src/hortum/encode.py
  src/hortum/productor/serializer.py
  src/hortum/productor/tests.py
  src/hortum/productor/urls.py
  src/hortum/productor/viewsets.py
Labels: Backend, Sprint 9, development

#186 #185 Review/Retrospective sprint 9
  docs/img/burndown_9.png
  docs/img/conhecimentos_9.png
  docs/img/retrospective_9.png
  docs/img/riscos_9.png
  docs/img/velocity_9.png
  docs/sprints/sprint_7/Review_sprint_7.md
  docs/sprints/sprint_8/Review_sprint_8.md
  docs/sprints/sprint_9/Review_sprint_9.md
  mkdocs.yml
Labels: SM, Sprint 10, documentation

#178 #92 [US06] - Atualizar Dados de Usuário
  src/hortum/urls.py
  src/hortum/users/serializer.py
  src/hortum/users/tests.py
  src/hortum/users/urls.py
  src/hortum/users/viewsets.py
Labels: Backend, Sprint 9

#187 #184 Documentação sobre o planning
  docs/sprints/sprint_10/Planning_sprint_10.md
  mkdocs.yml
Labels: SM, Sprint 10, documentation

#189 #104 [US18] - Adicionar anúncio a lista de favoritos
  src/hortum/announcement/serializer.py
  src/hortum/customer/migrations/0004_auto_20210416_1838.py
  src/hortum/customer/models.py
  src/hortum/customer/serializer.py
  src/hortum/customer/tests.py
  src/hortum/customer/urls.py
  src/hortum/customer/viewsets.py
  src/hortum/routers.py
  src/hortum/urls.py
  src/hortum/users/urls.py
Labels: Backend, Sprint 10, development

#188 #181 Alterar ordenação de anúncios na Homepage do comprador
  src/hortum/announcement/migrations/0003_auto_20210418_1416.py
  src/hortum/announcement/models.py
  src/hortum/announcement/tests.py
  src/hortum/announcement/viewsets.py
  src/hortum/settings.py
Labels: Backend, Sprint 10

#191 #103 [US17] - Adicionar Produtor a Lista de Favoritos
  src/hortum/customer/migrations/0005_auto_20210421_1413.py
  src/hortum/customer/models.py
  src/hortum/customer/serializer.py
  src/hortum/customer/tests.py
  src/hortum/customer/urls.py
  src/hortum/customer/viewsets.py
Labels: Backend, Sprint 10, development

#190 #98 visualizar anuncios produtor
  src/hortum/announcement/tests.py
  src/hortum/announcement/urls.py
  src/hortum/announcement/viewsets.py
  src/hortum/productor/tests.py
  src/hortum/productor/urls.py
  src/hortum/productor/viewsets.py
Labels: Backend, Sprint 10, development

#197 #195 Documento de review sprint 10
  docs/img/burndown_10.png
  docs/img/retrospective_10.png
  docs/img/riscos_10.png
  docs/img/velocity_10.png
  docs/sprints/sprint_10/Review_sprint_10.md
  mkdocs.yml
Labels: SM, Sprint 11, documentation

#198 #196 Adição do planning da sprint 11
  docs/sprints/sprint_11/Planning_sprint_11.md
  mkdocs.yml
Labels: SM, Sprint 11, documentation

#200 Feature/192 implementação swagger
  README.md
  requirements.txt
  src/hortum/settings.py
  src/hortum/urls.py
Labels: Backend, DevOps, Sprint 11, documentation

#199 #180/#107 [US21] - Denunciar usuário
  docs/Documento_de_arquitetura.md
  docs/img/diagrama_banco_de_dados.png
  docs/img/diagrama_casos_de_uso.png
  docs/img/diagrama_entidade_relacionamentos.png
  src/hortum/complaint/__init__.py
  src/hortum/complaint/admin.py
  src/hortum/complaint/apps.py
  src/hortum/complaint/migrations/0001_initial.py
  src/hortum/complaint/migrations/__init__.py
  src/hortum/complaint/models.py
  src/hortum/complaint/serializer.py
  src/hortum/complaint/tests.py
  src/hortum/complaint/urls.py
  src/hortum/complaint/viewsets.py
  src/hortum/settings.py
  src/hortum/urls.py
Labels: Backend, Sprint 10, Sprint 11, development, enhancement

#201 #89 [US02] - Apagar conta
  src/hortum/routers.py
  src/hortum/users/serializer.py
  src/hortum/users/tests.py
  src/hortum/users/urls.py
  src/hortum/users/viewsets.py
Labels: Backend, Sprint 11, development

#202 #194 Adição do numero de telefone
  src/hortum/announcement/migrations/0001_initial.py
  src/hortum/announcement/migrations/0002_announcement_idproductor.py
  src/hortum/announcement/migrations/0003_auto_20210418_1416.py
  src/hortum/announcement/serializer.py
  src/hortum/customer/migrations/0001_initial.py
  src/hortum/customer/migrations/0002_customer_idprodfav.py
  src/hortum/customer/migrations/0003_customer_user.py
  src/hortum/customer/migrations/0004_auto_20210416_1838.py
  src/hortum/customer/migrations/0005_auto_20210421_1413.py
  src/hortum/picture/migrations/0001_initial.py
  src/hortum/productor/migrations/0001_initial.py
  src/hortum/productor/migrations/0002_productor_user.py
  src/hortum/users/migrations/0001_initial.py
  src/hortum/users/migrations/0002_auto_20210428_1152.py
  src/hortum/users/models.py
  src/hortum/users/serializer.py
  src/hortum/users/tests.py
  src/hortum/users/viewsets.py
Labels: Backend, Sprint 11, development

#203 #183 Armazenamento de imagens
  .gitignore
  src/hortum/announcement/migrations/0001_initial.py
  src/hortum/announcement/migrations/0002_announcement_idproductor.py
  src/hortum/announcement/migrations/0003_auto_20210418_1416.py
  src/hortum/announcement/models.py
  src/hortum/announcement/serializer.py
  src/hortum/announcement/tests.py
  src/hortum/announcement/viewsets.py
  src/hortum/complaint/migrations/0001_initial.py
  src/hortum/complaint/models.py
  src/hortum/complaint/serializer.py
  src/hortum/customer/migrations/0001_initial.py
  src/hortum/customer/migrations/0002_customer_idprodfav.py
  src/hortum/customer/migrations/0003_customer_user.py
  src/hortum/customer/migrations/0004_auto_20210416_1838.py
  src/hortum/customer/migrations/0005_auto_20210421_1413.py
  src/hortum/customer/models.py
  src/hortum/customer/serializer.py
  src/hortum/customer/tests.py
  src/hortum/customer/viewsets.py
  src/hortum/img/person-male.png
  src/hortum/picture/__init__.py
  src/hortum/picture/admin.py
  src/hortum/picture/apps.py
  src/hortum/picture/migrations/0001_initial.py
  src/hortum/picture/migrations/__init__.py
  src/hortum/picture/models.py
  src/hortum/picture/serializer.py
  src/hortum/picture/tests.py
  src/hortum/picture/views.py
  src/hortum/productor/migrations/0001_initial.py
  src/hortum/productor/migrations/0002_productor_user.py
  src/hortum/productor/models.py
  src/hortum/productor/serializer.py
  src/hortum/productor/viewsets.py
  src/hortum/settings.py
  src/hortum/urls.py
  src/hortum/users/migrations/0001_initial.py
  src/hortum/users/models.py
  src/hortum/users/serializer.py
Labels: Backend, Sprint 11, development

#213 #210 Adicionando planning sprint 12
  docs/sprints/sprint_12/Planning_sprint_12.md
  mkdocs.yml
Labels: SM, Sprint 12, documentation
