Repository fga-eps-mds/2020.2-Hortum, pull requests merged in 2021-02, with the labels that each got.

#13 #9 User Story template
  .github/ISSUE_TEMPLATE/user-story-template.md
Labels: Sprint 1, documentation

#14 #7 Documentação da Sprint 0
  docs/sprints/sprint_0/Planning_sprint_0.md
  docs/sprints/sprint_0/Review_sprint_0.md
  docs/sprints/sprint_template.md
  docs/sprints/sprint_template_planning.md
  docs/sprints/sprint_template_review.md
  mkdocs.yml
Labels: SM, Sprint 1, documentation

#18 #10 Abertura do Documento de Visão
  docs/Documento_de_visao.md
  mkdocs.yml
Labels: Sprint 1, documentation

#16 #11 Adição do Documento de Arquitetura
  docs/Documento_de_arquitetura.md
  mkdocs.yml
Labels: Sprint 1, documentation

#33 #30 Arrumado os tópicos do Objetivos
  docs/sprints/sprint_1/Planning_sprint_1.md
Labels: Sprint 2, bug, documentation

#19 12 documento metodologia
  docs/Documento_de_arquitetura.md
  docs/Documento_metodologia.md
  mkdocs.yml
Labels: documentation

#32 #25 Adição Review Sprint 1
  docs/sprints/sprint_1/Review_sprint_1.md
  mkdocs.yml
Labels: Sprint 2, documentation

#34 #29 Padronização de documentos
  docs/Documento_de_arquitetura.md
  docs/Documento_de_visao.md
  docs/Documento_metodologia.md
  docs/sprints/sprint_0/Planning_sprint_0.md
  docs/sprints/sprint_0/Review_sprint_0.md
  docs/sprints/sprint_1/Planning_sprint_1.md
  docs/sprints/sprint_1/Review_sprint_1.md
Labels: Sprint 2, documentation

#36 #26 Adição do Planning da Sprint 2
  docs/sprints/sprint_2/Planning_sprint_2.md
  docs/sprints/sprint_template_planning.md
  docs/sprints/sprint_template_review.md
  mkdocs.yml
Labels: SM, Sprint 2, documentation

#37 #35 Modificação do Pull Request template como feedback do monitor
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
Labels: Sprint 2, feedback

#38 #23 Criado Documento de Protótipo
  docs/Prototipo.md
  docs/img/Baixa_fidelidade.png
  mkdocs.yml
Labels: Sprint 2, documentation, study

#40 #21 Criação da base para o django
  .gitignore
  requirements.txt
  src/hortum/__init__.py
  src/hortum/asgi.py
  src/hortum/assets/__init__.py
  src/hortum/assets/admin.py
  src/hortum/assets/apps.py
  src/hortum/assets/migrations/__init__.py
  src/hortum/assets/models.py
  src/hortum/assets/tests.py
  src/hortum/assets/views.py
  src/hortum/settings.py
  src/hortum/urls.py
  src/hortum/wsgi.py
  src/manage.py
Labels: Sprint 2, development, study

#39 #24 Evolução documento de arquitetura
  docs/Documento_de_arquitetura.md
Labels: Sprint 2, documentation

#49 #46 Complementado a licença com o nome do projeto
  LICENSE
Labels: Sprint 3, documentation

#51 #48 Adição da Review e Restrospective da Sprint 2
  docs/img/burndown_2.png
  docs/img/conhecimentos_2.png
  docs/img/retrospective_2.png
  docs/sprints/sprint_2/Review_sprint_2.md
  mkdocs.yml
Labels: SM, Sprint 3, documentation

#50 #17 Adição do Product Backlog
  docs/Product_Backlog.md
  mkdocs.yml
Labels: PO, Sprint 3, documentation

#52 #47 Adição do Planning da Sprint 3
  docs/sprints/sprint_3/Planning_sprint_3.md
  mkdocs.yml
Labels: SM, Sprint 3, documentation
