Repository fga-eps-mds/2020.2-Hortum, pull requests merged in 2021-05, with the labels that each got.

#215 #182 Implementação localização
  src/hortum/announcement/migrations/0001_initial.py
  src/hortum/announcement/migrations/0002_announcement_idproductor.py
  src/hortum/announcement/models.py
  src/hortum/announcement/serializer.py
  src/hortum/announcement/tests.py
  src/hortum/announcement/viewsets.py
  src/hortum/complaint/migrations/0001_initial.py
  src/hortum/complaint/migrations/0002_complaint_idproductor.py
  src/hortum/customer/migrations/0001_initial.py
  src/hortum/customer/migrations/0002_customer_idprodfav.py
  src/hortum/customer/migrations/0003_customer_user.py
  src/hortum/customer/tests.py
  src/hortum/productor/migrations/0001_initial.py
  src/hortum/productor/migrations/0002_productor_user.py
  src/hortum/productor/models.py
  src/hortum/productor/serializer.py
  src/hortum/users/migrations/0001_initial.py
  src/hortum/users/tests.py
Labels: Backend, Sprint 10

#217 #207 Atualização de documentação
  docs/Documento_de_arquitetura.md
  docs/Documento_de_visao.md
  docs/Documento_metodologia.md
  docs/Product_Backlog.md
  docs/img/diagrama_banco_de_dados.png
  docs/img/diagrama_entidade_relacionamentos.png
Labels: Sprint 12, documentation

#216 #163 Interações com Email
  src/hortum/announcement/tests.py
  src/hortum/complaint/tests.py
  src/hortum/customer/tests.py
  src/hortum/customer/viewsets.py
  src/hortum/productor/tests.py
  src/hortum/productor/urls.py
  src/hortum/productor/viewsets.py
  src/hortum/settings.py
  src/hortum/static/hortum/logo.png
  src/hortum/templates/hortum/user_already_verified_page.html
  src/hortum/templates/hortum/user_verify_page.html
  src/hortum/users/migrations/0002_user_is_verified.py
  src/hortum/users/models.py
  src/hortum/users/permissions.py
  src/hortum/users/serializer.py
  src/hortum/users/tests.py
  src/hortum/users/urls.py
  src/hortum/users/viewsets.py
Labels: Backend, Sprint 10, development

#228 #225 Review/retrospective sprint 12
  docs/img/burndown_12.png
  docs/img/retrospective_12.png
  docs/img/riscos_12.png
  docs/img/velocity_12.png
  docs/sprints/sprint_12/Review_sprint_12.md
  mkdocs.yml
Labels: SM, Sprint 13, documentation

#230 #226 Documentação planning 13
  docs/sprints/sprint_13/Planning_sprint_13.md
  mkdocs.yml
Labels: SM, Sprint 13, documentation

#218 [US05] Redefinir senha
  src/hortum/static/hortum/logo.png
  src/hortum/templates/hortum/email_template_name.htm
  src/hortum/templates/hortum/password_reset.html
  src/hortum/templates/hortum/password_reset_complete.html
  src/hortum/templates/hortum/password_reset_confirm.html
  src/hortum/templates/hortum/password_reset_done.html
  src/hortum/urls.py
  src/hortum/users/forms.py
  src/hortum/users/models.py
Labels: Backend, Sprint 12, enhancement

#233 [HOTFIX] #231 Corrigindo erro de registro
  src/hortum/customer/viewsets.py
  src/hortum/productor/viewsets.py
Labels: Backend, Hotfix, bug

#227 #100 [US14] - Pesquisar Localização
  src/hortum/announcement/tests.py
  src/hortum/announcement/urls.py
  src/hortum/announcement/viewsets.py
  src/hortum/routers.py
Labels: Backend, Sprint 12, development

#232 #209 Imagens
  .gitignore
  src/hortum/announcement/models.py
  src/hortum/announcement/serializer.py
  src/hortum/complaint/models.py
  src/hortum/users/migrations/0002_auto_20210505_2003.py
  src/hortum/users/models.py
  src/hortum/users/serializer.py
  src/images/person-male.png
Labels: Backend, Sprint 12, development

#234 #220 Diminuir tamanho dos nomes
  src/hortum/complaint/migrations/0001_initial.py
  src/hortum/complaint/models.py
  src/hortum/users/migrations/0001_initial.py
  src/hortum/users/migrations/0002_auto_20210505_2003.py
  src/hortum/users/models.py
Labels: Backend, Sprint 13, development

#235 #219 Deixar anúncio invisível
  src/hortum/announcement/serializer.py
Labels: Backend, Sprint 13, development

#236 #208 atualização das categorias
  src/hortum/announcement/migrations/0003_auto_20210504_0049.py
  src/hortum/announcement/models.py
  src/hortum/announcement/tests.py
  src/hortum/announcement/viewsets.py
  src/hortum/customer/tests.py
  src/hortum/users/tests.py
Labels: Backend, Sprint 13, development

#241 #239 Review sprint 13
  docs/img/burndown_13.png
  docs/img/conhecimentos_13.png
  docs/img/retrospective_13.png
  docs/img/riscos_13.png
  docs/img/velocity_13.png
  docs/sprints/sprint_13/Review_sprint_13.md
  mkdocs.yml
Labels: SM, Sprint 14, documentation

#243 #240 Adicionando documento do planning
  docs/sprints/sprint_14/Planning_sprint_14.md
  mkdocs.yml
Labels: SM, Sprint 14, documentation

#229 #221 Refatoração geral do backend
  .gitignore
  src/.coveragerc
  src/hortum/announcement/migrations/0001_initial.py
  src/hortum/announcement/migrations/0002_announcement_idproductor.py
  src/hortum/announcement/models.py
  src/hortum/announcement/serializer.py
  src/hortum/announcement/tests.py
  src/hortum/announcement/urls.py
  src/hortum/announcement/viewsets.py
  src/hortum/complaint/migrations/0001_initial.py
  src/hortum/complaint/migrations/0002_complaint_idproductor.py
  src/hortum/complaint/serializer.py
  src/hortum/complaint/tests.py
  src/hortum/complaint/urls.py
  src/hortum/complaint/viewsets.py
  src/hortum/customer/migrations/0001_initial.py
  src/hortum/customer/migrations/0002_customer_idprodfav.py
  src/hortum/customer/migrations/0003_customer_user.py
  src/hortum/customer/permissions.py
  src/hortum/customer/serializer.py
  src/hortum/customer/tests.py
  src/hortum/customer/urls.py
  src/hortum/customer/viewsets.py
  src/hortum/productor/migrations/0001_initial.py
  src/hortum/productor/migrations/0002_productor_user.py
  src/hortum/productor/permissions.py
  src/hortum/productor/serializer.py
  src/hortum/productor/tests.py
  src/hortum/productor/urls.py
  src/hortum/productor/viewsets.py
  src/hortum/routers.py
  src/hortum/settings.py
  src/hortum/urls.py
  src/hortum/users/forms.py
  src/hortum/users/migrations/0001_initial.py
  src/hortum/users/models.py
  src/hortum/users/permissions.py
  src/hortum/users/serializer.py
  src/hortum/users/tests.py
  src/hortum/users/urls.py
  src/hortum/users/validators.py
  src/hortum/users/viewsets.py
  src/hortum/validators.py
  src/manage.py
  src/scripts/create_superuser.sh
  src/scripts/startup.sh
Labels: Backend, Sprint 13, development

#244 Adição da Release 2
  README.md
Labels: Sprint 14, documentation

#245 #242 Documento de Post Mortem
  docs/Post_mortem.md
  mkdocs.yml
Labels: Sprint 14, documentation

#246 #222 adicionando link do app na play store ao README
  README.md
Labels: DevOps, Sprint 14, documentation

#248 #247 Correção documentação swagger
  src/hortum/announcement/serializer.py
Labels: bug
